### ISSUE TITLE
RT#42070: doesn't work with warn from XS code

### ISSUE THREAD

**Issue by kyzn** [hanfried/test-warn#1]
Hi! I tried to take a look at this RT issue. I was able to reproduce it, but I couldn't find a fix. Instead of commenting there, I figured I could move it here for more visibility.

 Here's the [message in RT](https://rt.cpan.org/Public/Bug/Display.html?ShowHeaders=1;id=42070):

    I don't know if it's a bug or undocumented limitation.
    But Test::Warn doesn't catch warn from XS code.
    
    See from example in module re::engine::Lua
    - t/flags.t : one TODO test
    - Lua.xs line #328 warn() call

If you install `re::engine::Lua`, and remove `TODO` in `flags.t`, test does fail.

***

I tried running:

    use re::engine::Lua;
    'aaa' =~ /a/i;

in both [`reply`](https://metacpan.org/pod/distribution/Reply/bin/reply) and `perl -de0`. It _did_ warn in reply, but not in -de0.
    

So.. Do you think it's worth adding a note to pod saying "XS warnings will not be caught"? Any other ideas on what might be causing this issue? I am not sure about what difference there is between XS warning and Perl warning.

**Comment by hanfried** [comment]
I added in https://github.com/hanfried/test-warn/commit/21c5eddc43235f1a3ea32eca181ba096b2ed6983 a note that XS warnings might not be caught.
If you provide me a standalone/test script demonstrating the problem I might try to fix it, allthough I won't promise anything - it's 15 years ago that I worked with XS.
Obviously, I welcome any PR.

**Comment by kyzn** [comment]
Thanks @hanfried! I'll take a look ~this weekend~ soon to see if I can deliver said test file.

**Comment by karenetheridge** [comment]
I'd be interested in adding this test to Test::Warnings as well.

**Comment by hanfried** [comment]
Test::Warnings is different project I'm not connected with.
As far as I can see, the issue should be solved now.
If there are no protests, I'll close in the next two weeks.

**Comment by karenetheridge** [comment]
> Test::Warnings is different project I'm not connected with.

Yes, I know. (It's mine.) I'm saying: when you have a test that demonstrates the issue, I would be interested in using it as well in Test::Warnings.

**Comment by kyzn** [comment]
Hi @hanfried, 

While I wasn't able to get around writing XS code that throws the actual warning, following test file seems to fail if you have `re::engine::Lua` installed:

```perl
use Test::More;
use Test::Warn;
use re::engine::Lua;

warning_is { 'aaa' =~ /a/i } "flags not supported by re::engine::Lua";

done_testing;
```

@karenetheridge, likewise, the following code also fails, and it gets an empty arrayref.

```perl
use Test::More;
use Test::Warnings qw/:all/;
use re::engine::Lua;

my $warning = warning { 'aaa' =~ /a/i };
like($warning, qr/^flags not supported/, 'we warned')
  or diag 'got warning(s): ', explain($warning);

done_testing;
```

This is a variation of [flags.t](https://metacpan.org/source/PERRAD/re-engine-Lua-0.17/t/flags.t) test file.

And this is how it looks on `reply`:
```
0> use re::engine::Lua;
1> 'aaa' =~ /a/i
flags not supported by re::engine::Lua
$res[0] = 1

2> 
```

**Comment by hanfried** [comment]
The XS code seems to completely ignore the sig handler.
To demonstrate look at the following snippet:
```
use re::engine::Lua;
$SIG{__WARN__} = sub {
    print STDERR "Bar";
    warn(@_);
};

'aaa' =~ /a/i;  # output directly to STDERR
warn("Foo");  # output goes first to above sig handler as seen in output with Bar before Foo
```
gives output as:
```
flags not supported by re::engine::Lua                                    
BarFoo at -e line 1.  
```
Test::Warn catches the sig handler https://github.com/hanfried/test-warn/blob/master/Warn.pm#L318 as it should be the only reliable source to catch warnings. (I don't parse STDERR as that could be anything).
Now, re::engine::Lua doesn't make any overwriting of warn, it uses directly the xs call in https://metacpan.org/source/PERRAD/re-engine-Lua-0.06/Lua.xs#L328
So, I assume that the XS handler doesn't call the `__WARN__`  sig handler at anyall.
I couldn't really understand the c source code for the xs handler and didn't find good information on the web, only stuff like those: https://www.perlmonks.org/?node_id=1160702 or https://github.com/samtools/tabix/issues/5
The last link gave me the idea to check what happens if I install the first sig handler before anything else with
```
use re::engine::Lua;
BEGIN { 
    $SIG{__WARN__} = sub {
        print STDERR "Bar";
        warn(@_);
    };
}

'aaa' =~ /a/i;
warn("Foo");
```
with the intended output
```
Barflags not supported by re::engine::Lua                                 
BarFoo at t/xs_warnings_via_re_engine_lua.t line 16.
```
Now, I probably would not want to have a global sig handler in Test::Warn in general, should I? As I would need to handle it in BEGIN block while compiling, I probably also can't give options like `use Test::Warn qw(global_sighandler)` without doing dirty stuff like source code parsing, can I?
But I could add a something like a `Test::WarnXS` where it is done.
As I'm a bit out of current Perl development or best practices, I'd like to hear some opinions about @kyzn @karenetheridge before starting.

**Comment by kyzn** [comment]
@hanfried, thanks a lot for your work! While I don't really have a clue on which way we should proceed, I did create a ticket for author of re-engine-Lua at RT: https://rt.cpan.org/Ticket/Display.html?id=125740

**Comment by karenetheridge** [comment]
The handler needs to be defined at compile time, since that's when the XS code issues the warning (when the regexp is compiled, not when it is run):

```
use strict;
use warnings;
use re::engine::Lua;
BEGIN {
  $SIG{__WARN__} = sub {
    print STDERR "got warning: @_";
    warn(@_);
  };
}

# this sub is never called - but the regexp is still compiled
sub foo {
  'aaa' =~ /a/i;
}
```

prints:

```
got warning: flags not supported by re::engine::Lua
flags not supported by re::engine::Lua
```

**Comment by wolfsage** [comment]
This does not look like a bug to me with re-engine-Lua.

The warning is being thrown during compile time (not run time) which is why wrapping the sig handler installation in a BEGIN block works.

This is the same problem you have if you do:

````
$SIG{__WARN__} = sub { warn "WARNED: @_\n" };

warn "A\n";
BEGIN { warn "B\n"; }
````

which gives...

````
B
WARNED: A
````

**Comment by hanfried** [comment]
Ah, so it is not a usual problem with XS warnings?
I don't catch the warnings as the warning is thrown in compile time, right?
So, we don't need a Test:WarnXS, but a Test::Warn::CompileTime, do we?

**Comment by karenetheridge** [comment]
>  So, we don't need a Test:WarnXS, but a Test::Warn::CompileTime, do we?

No. The user just needs to ensure that they use the appropriate sub at compile time. There's no way that you, in Test::Warn itself, can make code run sooner.

**Comment by kyzn** [comment]
Thanks a lot for all your comments. I understand this is then "not a bug" for Test-Warn or re-engine-Lua. I will be closing both this issue and RT ticket. Much learned! :slightly_smiling_face:
